OrdererOrgs:
  - Name: Orderer
    Domain: sample.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Orgone
    Domain: orgone.sample.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Orgtwo
    Domain: orgtwo.sample.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
