version: "2"

volumes:
  orderer.sample.com:
  peer0.orgone.sample.com:
  peer0.orgtwo.sample.com:

networks:
  sample:

services:
  orderer.sample.com:
    extends:
      file: base/docker-compose-base.yaml
      service: orderer.sample.com
    container_name: orderer.sample.com
    networks:
      - sample

  peer0.orgone.sample.com:
    container_name: peer0.orgone.sample.com
    extends:
      file: base/docker-compose-base.yaml
      service: peer0.orgone.sample.com
    environment:
      - CORE_LEDGER_HISTORY_ENABLEHISTORYDATABASE=true
    networks:
      - sample

  peer0.orgtwo.sample.com:
    container_name: peer0.orgtwo.sample.com
    extends:
      file: base/docker-compose-base.yaml
      service: peer0.orgtwo.sample.com
    environment:
      - CORE_LEDGER_HISTORY_ENABLEHISTORYDATABASE=true
    networks:
      - sample

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.orgone.sample.com:7051
      - CORE_PEER_LOCALMSPID=OrgoneMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgone.sample.com/peers/peer0.orgone.sample.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgone.sample.com/peers/peer0.orgone.sample.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgone.sample.com/peers/peer0.orgone.sample.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgone.sample.com/users/Admin@orgone.sample.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./../chaincode/:/opt/gopath/src/github.com/chaincode
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.sample.com
      - peer0.orgone.sample.com
      - peer0.orgtwo.sample.com
    networks:
      - sample
